"""add_event_code_to_jobs

Revision ID: 21e8362227ba
Revises: c7cd6820b3e8
Create Date: 2026-02-17 22:27:16.945292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e8362227ba'
down_revision: Union[str, None] = 'c7cd6820b3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('event_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'event_code')
    # ### end Alembic commands ###
