"""add_ip_address_to_jobs

Revision ID: c53eb37b1e32
Revises: 4aa03e185dcf
Create Date: 2026-03-06 12:00:11.819763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53eb37b1e32'
down_revision: Union[str, None] = '4aa03e185dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ip_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_ip_address'), 'jobs', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_ip_address'), table_name='jobs')
    op.drop_column('jobs', 'ip_address')
    # ### end Alembic commands ###
